listen_addresses = '*'
max_connections = 200

shared_buffers = 4GB
effective_cache_size = 12GB
maintenance_work_mem = 512MB
work_mem = 16MB

wal_level = replica
max_wal_size = 4GB
min_wal_size = 1GB

checkpoint_completion_target = 0.9

log_destination = 'stderr'
logging_collector = off
log_min_duration_statement = 1000
log_connections = on
log_disconnections = on

password_encryption = 'scram-sha-256'

timezone = 'Asia/Ho_Chi_Minh'
